AWSTemplateFormatVersion: "2010-09-09"
Transform:
- AWS::Serverless-2016-10-31
Description: API de Integracao do SIA com o Active Directory

Resources:
  alumniAdConsulta:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: s3://cl-app-codepipeline-deployment/developer/cl-alumniad/cl-alumniad.zip
      Role: arn:aws:iam::148100152883:role/service-role/alumniapiRole
        # Fn::ImportValue:
          #!Join ['-', ["alumniAD", !Ref 'AWS::Region', 'LambdaTrustRole']]

      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /usuario/-user-
            Method: get
